package camp.nextstep.lotto.ui.cli

import camp.nextstep.lotto.ticket.LottoTicket
import camp.nextstep.lotto.user.Gambler

object GamblerWriter {

    fun write(gambler: Gambler) {
        val autoTickets = gambler.tickets.filter { it.isAutoGenerated }
        val manuallyTickets = gambler.tickets.filterNot { it.isAutoGenerated }
        println("수동으로 ${manuallyTickets.size} 장, 자동으로 ${autoTickets.size} 장을 구매했습니다.")
        writeTickets(gambler.tickets)
    }

    private fun writeTickets(tickets: List<LottoTicket>) {
        for (ticket in tickets) {
            println(ticket.numbers)
        }
    }
}
