package camp.nextstep.lotto.ui.cli

import camp.nextstep.lotto.ticket.LottoTicket

object LottoTicketWriter {

    fun write(ticket: LottoTicket) {
        val numbers = ticket.numbers.lottoNumbers.joinToString(",\t") { it.value.toString() }
        val generatedType = if (ticket.isAutoGenerated) "자동" else "수동"
        println(
            """
            로또 티켓 { 발급 형태: $generatedType, 번호: [${"\t"}$numbers${"\t"}] }
            """.trimIndent()
        )
    }
}
