package lotto

import lotto.vo.Money

object LottoShop {
    val LOTTO_PRICE = Money(1000)
    fun sell(cash: Money, lottoPurchaseRequest: LottoPurchaseRequest): Lottos {
        val totalPurchaseLottoCount = cash / LOTTO_PRICE
        val manualLottos = lottoPurchaseRequest.lottos
        val remainingUnassignedLottoCount = (totalPurchaseLottoCount - manualLottos.size).toInt()
        require(remainingUnassignedLottoCount >= 0) { "금액이 부족합니다." }

        val autoGeneratedLottos = List((totalPurchaseLottoCount - manualLottos.size).toInt()) {
            Lotto.random()
        }

        return Lottos(
            manualLottos = manualLottos,
            autoGeneratedLottos = autoGeneratedLottos
        )
    }
}
