package lotto

import lotto.vo.Money

class RandomNumberLottoShop : LottoShop {

    override fun sell(cash: Money, purchaseCommand: PurchaseCommand): Pair<Lottos, Money> {
        val totalPurchaseLottoCount = cash / Lotto.PRICE
        val autoGeneratedLottos = List((totalPurchaseLottoCount).toInt()) {
            Lotto.random()
        }

        return Lottos(
            manualLottos = listOf(),
            autoGeneratedLottos = autoGeneratedLottos
        ) to cash - (Lotto.PRICE * totalPurchaseLottoCount.toInt())
    }
}
