package camp.nextstep.lotto.ticket

import camp.nextstep.lotto.number.LottoNumber
import camp.nextstep.lotto.number.LottoNumber.Companion.toLottoNumbers

class LottoTicket private constructor(private val _numbers: List<LottoNumber>, val isAutoGenerated: Boolean) {

    val numbers
        get() = _numbers.sortedBy { it.value }

    init {
        require(_numbers.toSet().size == LOTTO_NUMBERS) { "로또 티켓은 서로 다른 ${LOTTO_NUMBERS}개의 숫자를 가질 수 있습니다. numbers=$_numbers" }
    }

    companion object {

        const val LOTTO_NUMBERS = 6

        fun of(vararg numbers: Int): LottoTicket {
            return of(numbers.toList().toLottoNumbers())
        }

        fun of(numbers: List<LottoNumber>, isAutoGenerated: Boolean = true): LottoTicket {
            return LottoTicket(numbers, isAutoGenerated)
        }
    }
}
