package camp.nextstep.lotto.ticket

import camp.nextstep.lotto.number.LottoNumbers

class LottoTicket private constructor(val numbers: LottoNumbers, val isAutoGenerated: Boolean) {

    companion object {
        fun of(vararg numbers: Int): LottoTicket {
            return of(LottoNumbers.of(*numbers))
        }

        fun of(numbers: LottoNumbers, isAutoGenerated: Boolean = true): LottoTicket {
            return LottoTicket(numbers, isAutoGenerated)
        }
    }
}
