package camp.nextstep.lotto.ticket

import camp.nextstep.lotto.number.LottoNumbers

class LottoTicket private constructor(val numbers: LottoNumbers, val isAutoGenerated: Boolean) {

    init {
        require(numbers.toSet().size == LOTTO_NUMBERS) { "로또 티켓은 서로 다른 ${LOTTO_NUMBERS}개의 숫자를 가질 수 있습니다. numbers=$numbers" }
    }

    companion object {

        const val LOTTO_NUMBERS = 6

        fun of(vararg numbers: Int): LottoTicket {
            return of(LottoNumbers.of(*numbers))
        }

        fun of(numbers: LottoNumbers, isAutoGenerated: Boolean = true): LottoTicket {
            return LottoTicket(numbers, isAutoGenerated)
        }
    }
}
