package camp.nextstep.lotto.ticket

import camp.nextstep.lotto.number.LottoNumber
import camp.nextstep.lotto.number.LottoNumber.Companion.toLottoNumbers
import kotlin.random.Random

class LottoTicketMachine(private val numbersGenerator: NumbersGenerator = RandomNumbersGenerator(LottoNumber.LOTTO_NUMBER_RANGE, LottoTicket.LOTTO_NUMBERS)) {

    fun issueTicket(numbers: List<LottoNumber>): LottoTicket {
        return LottoTicket.of(numbers, isAutoGenerated = false)
    }

    fun issueTicket(): LottoTicket {
        val numbers = numbersGenerator.numbers()

        return LottoTicket.of(numbers, isAutoGenerated = true)
    }

    interface NumbersGenerator {
        fun numbers(): List<LottoNumber>
    }

    private class RandomNumbersGenerator(private val range: IntRange, private val n: Int) : NumbersGenerator {

        override fun numbers(): List<LottoNumber> {
            return generateSequence { Random(Random.Default.nextInt()).nextInt(range.first, range.last) }
                .distinct()
                .take(n)
                .sorted()
                .toList()
                .toLottoNumbers()
        }
    }
}
