package lotto.view

import lotto.GameResult
import lotto.Lotto
import lotto.Lottos
import lotto.ManualPurchaseCommand
import lotto.prize.Prize
import lotto.vo.LottoNumber
import lotto.vo.Money
import lotto.vo.WinningNumbers
import kotlin.math.floor

object ConsoleView : InputView, OutputView {
    override fun receiveMoney(): Money {
        println("구입금액을 입력해 주세요.")
        val moneyInput = readln()
            .toIntOrNull()
            ?: throw IllegalArgumentException("구입금액은 숫자여야 합니다.")
        return Money(moneyInput)
    }

    override fun receiveWinningNumbers(): WinningNumbers {
        println("지난 주 당첨 번호를 입력해 주세요.")
        val winningNumbers = readln()
            .split(", ")
            .map {
                it.toIntOrNull()
                    ?: throw IllegalArgumentException("당첨 번호는 숫자여야 합니다.")
            }
            .map(LottoNumber::from)

        println("보너스 볼을 입력해 주세요.")
        val bonusNumber = readln()
            .toIntOrNull()
            ?: throw IllegalArgumentException("보너스 볼은 숫자여야 합니다.")

        return WinningNumbers(winningNumbers, LottoNumber.from(bonusNumber))
    }

    override fun receivePurchaseCommand(): ManualPurchaseCommand {
        val manualLottoCount = receiveManualLottoCount()

        val manualLottos = receiveManualLottos(manualLottoCount)

        return ManualPurchaseCommand(
            manualLottos
        )
    }

    private fun receiveManualLottos(manualLottoCount: Int): List<Lotto> {
        println("수동으로 구매할 번호를 입력해 주세요.")
        val purchaseLottos = List(manualLottoCount) {
            val receivedNumbers = readln()
                .split(", ")
                .map {
                    it.toIntOrNull()
                        ?: throw IllegalArgumentException("로또 번호는 숫자여야 합니다.")
                }
                .map(LottoNumber::from)
            Lotto.from(receivedNumbers)
        }
        return purchaseLottos
    }

    private fun receiveManualLottoCount(): Int {
        println("수동으로 구매할 로또 수를 입력해 주세요.")
        val manualLottoCount = readln()
            .toIntOrNull()
            ?: throw IllegalArgumentException("로또 수는 숫자여야 합니다.")

        require(manualLottoCount > 0) { "구매할 로또 수는 양수여야 합니다." }
        return manualLottoCount
    }

    override fun showPurchased(lottos: Lottos) {
        val manualLottos = lottos.manualLottos
        val autoGeneratedLottos = lottos.autoGeneratedLottos
        println("수동으로 ${manualLottos.size}장, 자동으로 ${autoGeneratedLottos.size}개를 구매했습니다.")

        manualLottos.forEach {
            println(changeToConsoleFormat(it))
        }

        autoGeneratedLottos.forEach {
            println(changeToConsoleFormat(it))
        }
        println()
    }

    private fun changeToConsoleFormat(lotto: Lotto): String {
        return lotto.numbers
            .sorted()
            .joinToString(", ", "[", "]")
    }

    override fun show(result: GameResult) {
        println()
        println("당첨 통계")
        println("---------")
        result
            .prizes
            .forEach { (prize, count) ->
                println("${createMatchingDescriptionOf(prize)} (${prize.amount}원)- ${count}개")
            }
        println("총 수익률은 ${floor(result.profitRate * 100) / 100}입니다.")
    }

    private fun createMatchingDescriptionOf(prize: Prize) = "${prize.matchCount}개 일치${if (prize == Prize.MATCH_5_BONUS) ", 보너스 볼 일치" else ""}"
}
