package lotto

import io.kotest.core.spec.style.FreeSpec
import io.kotest.matchers.shouldBe
import lotto.test.lottoNumbersOf
import lotto.vo.Money

class LottoShopsTest : FreeSpec({
    "등록된 로또 판매점 순서대로 로또를 구매한 뒤, 구매한 로또와 잔돈을 반환한다." {
        val sut = LottoShopFacade(listOf(ManualLottoShop(), RandomNumberLottoShop()))
        val givenCash = Money(4500)
        val givenCommand = PurchaseCommand(
            listOf(
                Lotto.from(lottoNumbersOf(1, 2, 3, 4, 5, 6)),
            )
        )

        val (actualLottos, actualMoney) = sut.sell(givenCash, givenCommand)

        actualLottos.manualLottos shouldBe listOf(
            Lotto.from(lottoNumbersOf(1, 2, 3, 4, 5, 6)),
        )
        actualLottos.autoGeneratedLottos.size shouldBe 3
        actualMoney shouldBe Money(500)
    }
})
