package lotto

import io.kotest.core.spec.style.FreeSpec
import io.kotest.matchers.shouldBe
import lotto.test.lottoNumbersOf
import lotto.vo.Money

class ManualLottoShopTest : FreeSpec({
    "수동 로또를 판매한다. 구매하고자 하는 로또들의 총 가격보다 많은 금액을 받을 경우, 잔돈을 반환한다." {
        val sut = ManualLottoShop()
        val givenCash = Money(3500)
        val givenCommand = PurchaseCommand(
            listOf(
                Lotto.from(lottoNumbersOf(1, 2, 3, 4, 5, 6)),
                Lotto.from(lottoNumbersOf(7, 8, 9, 10, 11, 12))
            )
        )

        val result = sut.sell(givenCash, givenCommand)

        result shouldBe Pair(
            Lottos(
                manualLottos = givenCommand.lottos,
                autoGeneratedLottos = emptyList()
            ), Money(1500)
        )
    }
})
