package lotto

import io.kotest.core.spec.style.FreeSpec
import io.kotest.matchers.shouldBe
import lotto.test.lottoNumbersOf
import lotto.vo.Money

class RandomNumberLottoShopTest : FreeSpec({
    "주어진 금액만큼 무작위 로또를 구매한다." {
        val sut = RandomNumberLottoShop()
        val givenCash = Money(10500)

        val (resultLottos, remainingCash) = sut.sell(
            givenCash,
            PurchaseCommand(
                listOf(
                    Lotto.from(lottoNumbersOf(1, 2, 3, 4, 5, 6)),
                    Lotto.from(lottoNumbersOf(7, 8, 9, 10, 11, 12))
                )
            )
        )

        resultLottos.manualLottos shouldBe emptyList()
        resultLottos.autoGeneratedLottos.size shouldBe 10
        remainingCash shouldBe Money(500)

    }
})
