package lotto.domain

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.assertThrows

internal class PurchaseInformationTest {

    @Test
    fun `수동구매할 갯수의 정보를 리턴한다`() {
        val givenBudget = Budget.valueOf(4000)
        val manualCount = 2
        val purchaseInformation = PurchaseInformation(givenBudget, manualCount)

        assertThat(purchaseInformation.manualCount).isEqualTo(manualCount)
    }

    @Test
    fun `에산의 구매가능한 갯수보다 수동구매 갯수가 더 많으면 예외를 던진다`() {
        val givenBudget = Budget.valueOf(1000)
        val manualCount = 2

        assertThrows<IllegalArgumentException> { PurchaseInformation(givenBudget, manualCount) }
    }

    @Test
    fun `자동으로 생성된 갯수를 리턴한다`() {
        val givenBudget = Budget.valueOf(4000)
        val manualCount = 2
        val purchaseInformation = PurchaseInformation(givenBudget, manualCount)

        assertThat(purchaseInformation.getAutoGeneratedCount()).isEqualTo(2)
    }
}
