package lotto.domain

class LottoAutoGenerator(
    private val purchaseInformation: PurchaseInformation
) : LottoGenerator {

    override fun generateLottos(): List<Lotto> {
        return (1..purchaseInformation.getAutoGeneratedCount())
            .map { RandomNumberGenerator.generateNumbers() }
            .map { Lotto(it) }
    }
}
