package lotto.domain

import lotto.util.NumberGenerator
import lotto.util.RandomNumberGenerator

class LottoFactory(
    private val autoGeneratedLottoCount: Int,
    private val manualLottoList: List<List<Int>>,
    private val numberGenerator: NumberGenerator = RandomNumberGenerator(),
) {
    fun createLottoList(): List<Lotto> {
        return buildList {
            addAll(manualLottoList.map { fromList(it) })
            addAll(autoGeneratedLottoList())
        }
    }

    private fun autoGeneratedLottoList(): List<Lotto> {
        check(autoGeneratedLottoCount > 0) { "수동으로 생성하는 로또의 개수는 전체 로또 수를 초과할 수 없습니다." }
        return List(autoGeneratedLottoCount) {
            numberGenerator
                .getNumbers(Lotto.LOTTO_COUNT)
                .let { list -> Lotto(list.map { LottoNumber.from(it) }) }
        }
    }

    companion object {
        fun fromList(list: List<Int>): Lotto {
            return Lotto(list.map { LottoNumber(it) })
        }
    }
}
