package lotto.domain

class LottoGenerator(
    private val lottoNumberGenerator: LottoNumberGenerator
) {
    fun generateLottos(purchaseInformation: PurchaseInformation): List<Lotto> {
        return (1..purchaseInformation.getAutoGeneratedCount())
            .map { lottoNumberGenerator.generateNumbers() }
            .map { Lotto(it) }
    }
}
