package lotto.domain

import lotto.util.NumberGenerator
import lotto.util.RandomNumberGenerator

class LottoFactory(
    private val autoGeneratedLottoCount: Int,
    private val manualLottoList: List<List<Int>>,
    private val numberGenerator: NumberGenerator = RandomNumberGenerator(),
) {
    fun createLottoList(): List<Lotto> {
        return buildList {
            addAll(manualLottoList.map { fromList(it) })
            addAll(autoGeneratedLottoList())
        }
    }

    private fun autoGeneratedLottoList() =
        List(autoGeneratedLottoCount) {
            numberGenerator
                .getNumbers(Lotto.LOTTO_COUNT)
                .let { list -> Lotto(list.map { LottoNumber.from(it) }) }
        }

    companion object {
        fun fromList(list: List<Int>): Lotto {
            return Lotto(list.map { LottoNumber(it) })
        }
    }
}
