package lotto.domain

class PurchaseInformation(val budget: Budget, val manualCount: Int, val textLottos: List<String> = emptyList()) {
    init {
        require(budget.validateManualCount(manualCount))
    }

    fun getAutoGeneratedCount(): Int {
        return budget.getRemainCount(manualCount)
    }
}
