package lotto.domain

const val FIRST_GRADE_MATCHING_COUNT = 6
const val SECOND_GRADE_MATCHING_COUNT = 5
const val THIRD_GRADE_MATCHING_COUNT = 4
const val FOURTH_GRADE_MATCHING_COUNT = 3
const val FIFTH_GRADE_MATCHING_COUNT = 2
const val SIXTH_GRADE_MATCHING_COUNT = 1
const val NONE_GRADE_MATCHING_COUNT = 0

const val FIRST_WIN_PRICE = 2_000_000_000
const val SECOND_WIN_PRICE = 1_500_000
const val THIRD_WIN_PRICE = 50_000
const val FOURTH_WIN_PRICE = 5_000
const val NONE_WIN_PRICE = 0